(DIO-1066) Update vanagon to go through ABS for VMs
puppetlabs/vanagon pull request #662
Opened 2020-10-21 19:02 UTC by sbeaulie

Before this change, the ABS engine was partially implemented.
It now includes the select_target and teardown methods needed for
vanagon build lifecycle.

This engine is thus a level of abstraction that supports any downstream
engine (vmpooler, nspooler, AWS) and is forward compatible with
ondemand Vmpooler pools.

The ABS token is read from env var ABS_TOKEN or the first line of ~/.vanagon-token
or the vmfloaty config (using top-level token or the first abs type service found)

The vmpooler token optionaly can be provided through an env var VMPOOLER_TOKEN
or the second line of ~/.vanagon-token or via vmfloaty's existing vmpooler_fallback config

The ABS request is done and checked for up to an hour, with feedback given on the
availability of resources. Teardown is done at the end using the job_id.

Users can track vm usage via bitbar or floaty if they provide a vmpooler token.

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

2020-10-21 19:05 UTC, sbeaulie commented
@beechtom would you mind testing this code for your bolt-vanagon project? I tried it myself with `bundle exec ./bin/vanagon build puppet-bolt fedora-30-x86_64 --engine always_be_scheduling --preserve never` and it was successful.

2020-10-22 00:00 UTC, puppetcla commented
Waiting for CLA signature by @sbeaulie

@sbeaulie - We require a Contributor License Agreement (CLA) for people who contribute to Puppet, but we have an easy click-through license with instructions, which is available at https://cla.puppet.com/

Note: if your contribution is trivial and you think it may be exempt from the CLA, please post a short reply to this comment with details. http://docs.puppet.com/community/trivial_patch_exemption.html

2020-10-22 17:10 UTC, mattkirby approved these changes

2020-10-22 17:47 UTC, beechtom approved these changes

2020-10-23 19:07 UTC, e-gris requested changes
Looks great. Only the CHANGELOG is a required change.

The rest are stylistic comments which are part of a direction I'm hoping to nudge this (and other RE projects) into. 

They are wholly optional and I didn't mark each one.

2020-10-23 19:07 UTC, e-gris commented on lib/vanagon/engine/always_be_scheduling.rb
> +        pooler
Prefer guardian clauses over if/else:

```ruby
return '' unless res_body['ok']
 
@target = res_body[build_host_name]['hostname']
Vanagon::Driver.logger.info "Reserving #{@target} (#{build_host_name}) [#{@token ? 'token used' : 'no token used'}]"
return pooler
```

2020-10-23 21:37 UTC, e-gris approved these changes

2020-10-23 21:38 UTC, e-gris commented
Merge at will.

2020-10-28 17:45 UTC, merged